class Guide {
  final String name;
  final String steps;
  const Guide(this.name, this.steps);
}

// Menus change over time. These are the usual paths; if a step is missing,
// search the service's Help page for "cancel".
const List<Guide> kGuides = [
  Guide('Google Play (any Android app)',
      'Open Play Store > tap your profile picture > Payments & subscriptions > Subscriptions > pick the app > Cancel subscription.'),
  Guide('Apple App Store (any iPhone app)',
      'iPhone Settings > tap your name > Subscriptions > pick the service > Cancel Subscription.'),
  Guide('Netflix',
      'Sign in at netflix.com > profile icon > Account > Cancel Membership. If you pay through Google Play or a phone company, cancel there instead.'),
  Guide('Spotify',
      'Sign in at spotify.com in a browser > Account > Manage your plan > Cancel Premium. It usually cannot be done inside the app.'),
  Guide('YouTube Premium',
      'youtube.com > profile picture > Purchases and memberships > Memberships > YouTube Premium > Deactivate.'),
  Guide('Disney+',
      'disneyplus.com > profile > Account > Subscription > Cancel Subscription.'),
  Guide('Amazon Prime',
      'amazon.com > Account & Lists > Prime Membership > Manage Membership > End Membership.'),
  Guide('Hulu', 'hulu.com > Account > Your Subscription > Cancel.'),
  Guide('Max (HBO Max)',
      'max.com > profile > Subscription > Manage Subscription > Cancel Subscription.'),
  Guide('Paramount+',
      'paramountplus.com > profile > Account > Cancel Subscription.'),
  Guide('Peacock',
      'peacocktv.com > profile > Account > Plans & Payment > Cancel.'),
  Guide('Apple TV+ / Apple Music / Apple One',
      'iPhone Settings > tap your name > Subscriptions > pick the service > Cancel Subscription.'),
  Guide('Crunchyroll',
      'crunchyroll.com > Settings > Membership Info > Cancel Membership.'),
  Guide('Tidal', 'account.tidal.com > Subscription > Cancel subscription.'),
  Guide('Deezer',
      'deezer.com > Account Settings > My subscription > Cancel. If billed through a store, cancel there.'),
  Guide('Google One',
      'one.google.com > Settings > Cancel membership.'),
  Guide('Microsoft 365',
      'account.microsoft.com/services > find Microsoft 365 > Manage > Cancel subscription.'),
  Guide('Xbox Game Pass',
      'account.microsoft.com/services > Xbox Game Pass > Manage > Cancel.'),
  Guide('PlayStation Plus',
      'Console: Settings > Users and Accounts > Account > Payment and Subscriptions > Subscriptions > PlayStation Plus > Cancel.'),
  Guide('Nintendo Switch Online',
      'Nintendo eShop > your profile > Shop Menu > Nintendo Switch Online > turn off auto-renewal.'),
  Guide('Adobe Creative Cloud',
      'account.adobe.com > Plans > Manage plan > Cancel plan. Yearly plans may charge an early-cancellation fee.'),
  Guide('Dropbox', 'dropbox.com > profile > Settings > Plan > Cancel plan.'),
  Guide('Canva Pro',
      'canva.com > Account settings > Billing & plans > Cancel subscription.'),
  Guide('Notion',
      'Settings > Plans > Change plan > switch to Free.'),
  Guide('Zoom',
      'zoom.us > Account Management > Billing > Current Plans > Cancel Subscription.'),
  Guide('Grammarly',
      'grammarly.com > Account > Subscription > Cancel Subscription.'),
  Guide('ChatGPT Plus',
      'chatgpt.com > profile menu > Settings or My plan > Manage subscription > Cancel. If you subscribed in the mobile app, cancel in the Play Store or App Store.'),
  Guide('Claude Pro',
      'claude.ai > Settings > Billing > Cancel plan. If you subscribed through the mobile app, cancel in the Play Store or App Store.'),
  Guide('Duolingo Super',
      'Cancel where you bought it: Google Play or App Store subscriptions, or duolingo.com > Settings > Super Duolingo.'),
  Guide('LinkedIn Premium',
      'LinkedIn > Me > Settings > Subscriptions & payments > Cancel subscription.'),
  Guide('Audible',
      'audible.com > Account Details > Cancel Membership.'),
  Guide('Kindle Unlimited',
      'amazon.com > Account & Lists > Memberships & Subscriptions > Kindle Unlimited > Cancel.'),
  Guide('Strava',
      'strava.com > Settings > My Account > Manage Membership > Cancel subscription.'),
  Guide('NordVPN',
      'my.nordaccount.com > Billing > Subscriptions > Manage > Cancel auto-renewal.'),
  Guide('ExpressVPN',
      'Sign in to your ExpressVPN account on the website > Subscription > turn off auto-renewal.'),
  Guide('Telegram Premium',
      'It is billed through the store you used: cancel in Google Play or App Store subscriptions.'),
  Guide('X Premium',
      'X > Settings > Premium > Manage subscription. If bought in the app, cancel in the Play Store or App Store.'),
  Guide('Snapchat+',
      'Snapchat > Settings > Snapchat+ > Manage subscription, or cancel in Google Play or App Store.'),
  Guide('Discord Nitro',
      'Discord > User Settings > Subscriptions > Nitro > Cancel.'),
  Guide('Medium',
      'medium.com > profile > Settings > Membership > Cancel membership.'),
  Guide('Coursera Plus',
      'coursera.org > profile > Settings > Subscriptions > Cancel.'),
  Guide('Skillshare',
      'skillshare.com > profile > Settings > Payments > Cancel membership.'),
  Guide('Headspace',
      'Cancel where you bought it: headspace.com > Account > Subscription, or Google Play / App Store.'),
  Guide('Calm',
      'calm.com > Profile > Manage Subscription > Cancel. If billed through a store, cancel there.'),
  Guide('Peloton', 'Peloton account > Membership > Cancel.'),
  Guide('Tinder',
      'Tinder > Profile > Settings > Manage Payment Account. If billed through a store, cancel in Google Play or App Store.'),
  Guide('Uber One',
      'Uber app > Account > Uber One > Manage membership > End membership.'),
  Guide('DoorDash DashPass',
      'DoorDash > Account > Manage DashPass > End subscription.'),
];
